### PR TITLE
Update of the French translation.

### PR DESCRIPTION
**Pull request by viroulep**
Update French translation to april, 3rd 2014.
Various typos fixed, thanks to Antoine Simon-Chautemps.

### CODE REVIEW

**Comment by lgarron** [comment]
@timhabermaas Do you have time to handle this one?

**Comment by timhabermaas** [comment]
@lgarron Yes, I'll take care of it.

**Comment by lgarron** [comment]
@timhabermaas Are you also still able to push the change?

**Comment by timhabermaas** [comment]
@lgarron I think I am. At least I can still log into the server. I'm currently waiting for pandoc to install (reinstalled my computer recently).

**Comment by timhabermaas** [comment]
@viroulep Everything's up and running: https://www.worldcubeassociation.org/regulations/translations/french/

Merci!

**Comment by viroulep** [comment]
Thanks to both of you ;)

2015-01-26 23:16 GMT+01:00 Tim Habermaas <notifications@github.com>:

**Pull request merged**
